export type RawParticleRole =
  | "COMPOUND_COMPLEMENT_PARTICLE"
  | "INDICATIVE_PARTICLE"
  | "OPTATIVE_PARTICLE"
  | "CONTEXT_PARTICLE"
  | "DIRECT_OBJECT_PARTICLE"
  | "AND_PARTICLE"
  | "OR_PARTICLE";
export type ParticleRole = RawParticleRole | "VOCATIVE_PARTICLE";
export type SubstantiveRole =
  | "SUBJECT"
  | "PREDICATE"
  | "CONTEXT_SUBJECT"
  | "CONTEXT_PREDICATE"
  | "COMPLEMENT"
  | "DIRECT_OBJECT"
  | "VOCATIVE"
  | "INFINITIVE"
  | "PREPOSITIONAL_OBJECT";
export type Role =
  | ParticleRole
  | SubstantiveRole
  | "NEGATIVE"
  | "INTERROGATIVE"
  | "INTERROGATIVE_REPETITION";

export const VOCATIVE = "VOCATIVE";
export const PREDICATE = "PREDICATE";
export const COMPLEMENT = "COMPLEMENT";
export const SUBJECT = "SUBJECT";
export const INFINITIVE = "INFINITIVE";
export const DIRECT_OBJECT = "DIRECT_OBJECT";
export const PREPOSITIONAL_OBJECT = "PREPOSITIONAL_OBJECT";
export const NEGATIVE = "NEGATIVE";
export const INTERROGATIVE = "INTERROGATIVE";
export const INTERROGATIVE_REPETITION = "INTERROGATIVE_REPETITION";
export const VOCATIVE_PARTICLE = "VOCATIVE_PARTICLE";
export const INDICATIVE_PARTICLE = "INDICATIVE_PARTICLE";
export const OPTATIVE_PARTICLE = "OPTATIVE_PARTICLE";
export const DIRECT_OBJECT_PARTICLE = "DIRECT_OBJECT_PARTICLE";
export const COMPOUND_COMPLEMENT_PARTICLE = "COMPOUND_COMPLEMENT_PARTICLE";
export const AND_PARTICLE = "AND_PARTICLE";
export const OR_PARTICLE = "OR_PARTICLE";
export const CONTEXT_PARTICLE = "CONTEXT_PARTICLE";
export const CONTEXT_SUBJECT = "CONTEXT_SUBJECT";
export const CONTEXT_PREDICATE = "CONTEXT_PREDICATE";
